name: Build, Test, and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Use Node.js latest 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Execute unit tests
        run: npm run test:unit

      - name: Display SoftUni username
        run: echo 'peterstoyanov'

  run_ui_tests:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Use Node.js latest 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Start the application
        run: npm run start &

      - name: Wait for server to start
        run: sleep 5 # wait for the server to start properly

      - name: Execute UI tests
        run: npm run test:ui
